In [44]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
import operator
import geopy.distance
from xgboost.sklearn import XGBRegressor
# import xgboost as xgb

# import warnings
# warnings.filterwarnings("ignore")

pd.options.display.max_columns = 200
%matplotlib inline

In [16]:
dtypes = {'start_datetime': 'str'}
parse_dates = ['start_datetime']
train_orig = pd.read_csv('clean_train.csv', dtype=dtypes, parse_dates=parse_dates)
train_orig.shape

(12905715, 15)

In [19]:
train_orig['start_datetime'] = pd.to_datetime(train_orig['start_timestamp'], unit='s')

In [20]:
# Convert to EST as all locations are in New York area
train_orig['start_datetime'] = train_orig['start_datetime'].dt.tz_localize('UTC').dt.tz_convert('US/Eastern')

In [21]:
train_orig['start_year'] = train_orig['start_datetime'].dt.year
train_orig['start_month'] = train_orig['start_datetime'].dt.month
train_orig['start_day'] = train_orig['start_datetime'].dt.day
train_orig['start_weekday'] = train_orig['start_datetime'].dt.weekday
train_orig['start_hour'] = train_orig['start_datetime'].dt.hour

In [17]:
train_orig.head()

,row_id,start_lng,start_lat,end_lng,end_lat,start_timestamp,duration,duration_min,start_datetime,start_year,start_month,start_day,start_weekday,start_hour,dist
0,0,-74.009087,40.713818,-74.004326,40.719986,1420950819,112,1.866667,2015-01-11 04:33:39,2015,1,11,6,4,794
1,1,-73.971176,40.762428,-74.004181,40.742653,1420950819,1159,19.316667,2015-01-11 04:33:39,2015,1,11,6,4,3548
2,2,-73.994957,40.745079,-73.999939,40.734650,1421377541,281,4.683333,2015-01-16 03:05:41,2015,1,16,4,3,1232
3,3,-73.991127,40.750080,-73.988609,40.734890,1421377542,636,10.600000,2015-01-16 03:05:42,2015,1,16,4,3,1700
4,4,-73.945511,40.773724,-73.987434,40.755707,1422173586,705,11.750000,2015-01-25 08:13:06,2015,1,25,6,8,4066

In [31]:
weekday_map = {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}
encoding_weekday = pd.get_dummies(train_orig.start_weekday)
encoding_weekday.rename(columns=weekday_map, inplace=True)
train_orig = pd.merge(train_orig, encoding_weekday, left_index=True, right_index=True)
train_orig.shape

(12905715, 22)

In [33]:
month_map = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}
encoding_month = pd.get_dummies(train_orig.start_month)
encoding_month.rename(columns=month_map, inplace=True)
train_orig = pd.merge(train_orig, encoding_month, left_index=True, right_index=True)
train_orig.shape

(12905715, 34)

In [40]:
for i in range(1,25):
    print(str(i)+": 'hour"+str(i)+"',")

1: 'hour1',
2: 'hour2',
3: 'hour3',
4: 'hour4',
5: 'hour5',
6: 'hour6',
7: 'hour7',
8: 'hour8',
9: 'hour9',
10: 'hour10',
11: 'hour11',
12: 'hour12',
13: 'hour13',
14: 'hour14',
15: 'hour15',
16: 'hour16',
17: 'hour17',
18: 'hour18',
19: 'hour19',
20: 'hour20',
21: 'hour21',
22: 'hour22',
23: 'hour23',
24: 'hour24',

In [41]:
hour_map = {1: 'hour1',
            2: 'hour2',
            3: 'hour3',
            4: 'hour4',
            5: 'hour5',
            6: 'hour6',
            7: 'hour7',
            8: 'hour8',
            9: 'hour9',
            10: 'hour10',
            11: 'hour11',
            12: 'hour12',
            13: 'hour13',
            14: 'hour14',
            15: 'hour15',
            16: 'hour16',
            17: 'hour17',
            18: 'hour18',
            19: 'hour19',
            20: 'hour20',
            21: 'hour21',
            22: 'hour22',
            23: 'hour23',
            0: 'hour0'}
encoding_hour = pd.get_dummies(train_orig.start_hour)
encoding_hour.rename(columns=hour_map, inplace=True)
train_orig = pd.merge(train_orig, encoding_hour, left_index=True, right_index=True)
train_orig.shape

(12905715, 58)

In [42]:
train_orig.head()

,row_id,start_lng,start_lat,end_lng,end_lat,start_timestamp,duration,duration_min,start_datetime,start_year,start_month,start_day,start_weekday,start_hour,dist,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,0,hour1,hour2,hour3,hour4,hour5,hour6,hour7,hour8,hour9,hour10,hour11,hour12,hour13,hour14,hour15,hour16,hour17,hour18,hour19,hour20,hour21,hour22,hour23
0,0,-74.009087,40.713818,-74.004326,40.719986,1420950819,112,1.866667,2015-01-10 23:33:39-05:00,2015,1,10,5,23,794,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,1,-73.971176,40.762428,-74.004181,40.742653,1420950819,1159,19.316667,2015-01-10 23:33:39-05:00,2015,1,10,5,23,3548,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,2,-73.994957,40.745079,-73.999939,40.734650,1421377541,281,4.683333,2015-01-15 22:05:41-05:00,2015,1,15,3,22,1232,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,3,-73.991127,40.750080,-73.988609,40.734890,1421377542,636,10.600000,2015-01-15 22:05:42-05:00,2015,1,15,3,22,1700,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,4,-73.945511,40.773724,-73.987434,40.755707,1422173586,705,11.750000,2015-01-25 03:13:06-05:00,2015,1,25,6,3,4066,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
train_orig.to_csv('clean_train3.csv', index=None)

In [45]:
del train_orig['duration_min']
del train_orig['start_timestamp']
del train_orig['start_datetime']
del train_orig['start_year']
del train_orig['start_month']
del train_orig['start_day']
del train_orig['start_weekday']
del train_orig['start_hour']

In [46]:
# Split data to train and test sets
y_all = train_orig['duration']
x_all = train_orig.drop(['row_id', 'duration'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x_all, y_all, test_size=0.1, random_state=2018)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((11615143, 48), (1290572, 48), (11615143,), (1290572,))

# XGBOOST

### Simple model

In [50]:
xgb_model = XGBRegressor(n_estimators=100, max_depth=3, learning_rate=0.1, colsample_bytree=1, subsample=0.7, gamma=0, n_jobs=3)
xgb_model = xgb_model.fit(x_train, y_train)

KeyboardInterrupt:

In [ ]:
pred_train = xgb_model.predict(x_train)
print('Train Mean Absolute Error:', mean_absolute_error(y_train, pred_train))

In [ ]:
pred_test = xgb_model.predict(x_test)
print('Test Mean Absolute Error:', mean_absolute_error(y_test, pred_test))

### HyperParameter Tuning

In [47]:
params = {  
    'n_estimators': range(80, 121, 10),
    'max_depth': range(1,2),
    'learning_rate': np.arange(0.01,0.3, 0.01),
    'colsample_bytree': np.arange(0.3, 0.8, 0.05),
    'subsample': np.arange(0.3, 0.8, 0.05),
    'gamma': range(0, 10)
#     'reg_alpha': from_zero_positive,
#     "min_child_weight": from_zero_positive,
}
iters = 100

xgbreg = XGBRegressor()

# Manhattan Distance

In [53]:
from geopy.distance import great_circle

In [129]:
newport_ri = (40.0, 0)
cleveland_oh = (40.01, 0)
# 864456.76162966
# 1047.5288724585898

In [130]:
%%time
great_circle(newport_ri, cleveland_oh).m

CPU times: user 50 µs, sys: 0 ns, total: 50 µs
Wall time: 53.9 µs

1112.262553046778

In [66]:
%%time
geopy.distance.vincenty(newport_ri, cleveland_oh).m

CPU times: user 62 µs, sys: 0 ns, total: 62 µs
Wall time: 64.8 µs

684.9467770943194

# Explore Geopy

In [51]:
train_orig.head()

,row_id,start_lng,start_lat,end_lng,end_lat,duration,dist,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,0,hour1,hour2,hour3,hour4,hour5,hour6,hour7,hour8,hour9,hour10,hour11,hour12,hour13,hour14,hour15,hour16,hour17,hour18,hour19,hour20,hour21,hour22,hour23
0,0,-74.009087,40.713818,-74.004326,40.719986,112,794,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,1,-73.971176,40.762428,-74.004181,40.742653,1159,3548,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,2,-73.994957,40.745079,-73.999939,40.734650,281,1232,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,3,-73.991127,40.750080,-73.988609,40.734890,636,1700,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,4,-73.945511,40.773724,-73.987434,40.755707,705,4066,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [70]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()

In [ ]:
location = geolocator.reverse("52.509669, 13.376294")
print(location.address)
# Potsdamer Platz, Mitte, Berlin, 10117, Deutschland, European Union
print((location.latitude, location.longitude))
# (52.5094982, 13.3765983)
print(location.raw)
# {'place_id': '654513', 'osm_type': 'node', ...}

In [79]:
from geopy.geocoders import GoogleV3
geolocator =  GoogleV3()

In [86]:
location = geolocator.geocode('73.945511, 40.773724')
location

Location(Unnamed Road, Kyrgyzstan, (40.8155502, 73.97858889999999, 0.0))

In [114]:
import reverse_geocoder as rg
i=2
coordinates = (small['start_lat'].iloc[i], small['start_lng'].iloc[i])
# coordinates = (41.773724, -73.945511)

results = rg.search(coordinates) # default mode = 2

print (results)

[OrderedDict([('lat', '40.71427'), ('lon', '-74.00597'), ('name', 'New York City'), ('admin1', 'New York'), ('admin2', ''), ('cc', 'US')])]

In [101]:
results[0]['name'], results[0]['admin1']

('Hyde Park', 'New York')

In [133]:
small = train_orig[:10000]
small.shape

(10000, 50)

In [134]:
import reverse_geocoder as rg
def get_location(row):
    coordinates = (row['start_lat'], row['start_lng'])
    results = rg.search(coordinates)
    return results[0]['name'], results[0]['admin1'], results[0]['admin2']

In [135]:
%%time
# small['start_region'], small['start_admin1'], small['start_admin2'] = zip(*small.apply(get_location, axis=1))
small['start_region'] = small.apply(get_location, axis=1)

CPU times: user 56.1 s, sys: 6min 41s, total: 7min 37s
Wall time: 31min 42s

/Users/tamirlan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [136]:
train_orig.start_lat.max()

41.031418000000002

In [137]:
desc = train_orig.describe()
desc

,row_id,start_lng,start_lat,end_lng,end_lat,duration,dist,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,0,hour1,hour2,hour3,hour4,hour5,hour6,hour7,hour8,hour9,hour10,hour11,hour12,hour13,hour14,hour15,hour16,hour17,hour18,hour19,hour20,hour21,hour22,hour23
count,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07,1.290572e+07
mean,6.452857e+06,-7.397382e+01,4.075065e+01,-7.397358e+01,4.075141e+01,8.421420e+02,3.454856e+03,1.248555e-01,1.339236e-01,1.427376e-01,1.480157e-01,1.497761e-01,1.556159e-01,1.450756e-01,8.674963e-02,8.487162e-02,9.122292e-02,8.941233e-02,9.036772e-02,8.437231e-02,7.928054e-02,7.657515e-02,7.685580e-02,8.439866e-02,7.753759e-02,7.835575e-02,5.809488e-02,5.597838e-02,4.876545e-02,3.820858e-02,2.791546e-02,2.083372e-02,1.504620e-02,1.120783e-02,1.044591e-02,2.232306e-02,3.703793e-02,4.502083e-02,4.613166e-02,4.558337e-02,4.733360e-02,4.931249e-02,4.917411e-02,5.078603e-02,4.845481e-02,4.219828e-02,5.009579e-02,5.986945e-02,6.185655e-02,5.832563e-02
std,3.725559e+06,3.800296e-02,2.789741e-02,3.589918e-02,3.192092e-02,7.127489e+02,3.895369e+03,3.305551e-01,3.405702e-01,3.498051e-01,3.551155e-01,3.568519e-01,3.624908e-01,3.521770e-01,2.814678e-01,2.786906e-01,2.879259e-01,2.853380e-01,2.867079e-01,2.779454e-01,2.701761e-01,2.659161e-01,2.663625e-01,2.779848e-01,2.674425e-01,2.687306e-01,2.339228e-01,2.298800e-01,2.153773e-01,1.916995e-01,1.647307e-01,1.428274e-01,1.217367e-01,1.052721e-01,1.016700e-01,1.477320e-01,1.888548e-01,2.073498e-01,2.097702e-01,2.085798e-01,2.123514e-01,2.165197e-01,2.162314e-01,2.195605e-01,2.147253e-01,2.010413e-01,2.181426e-01,2.372448e-01,2.408948e-01,2.343582e-01
min,0.000000e+00,-7.451462e+01,4.036892e+01,-7.451785e+01,4.036887e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.226428e+06,-7.399206e+01,4.073697e+01,-7.399143e+01,4.073552e+01,4.000000e+02,1.253000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.452857e+06,-7.398196e+01,4.075359e+01,-7.398009e+01,4.075408e+01,6.650000e+02,2.134000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,9.679286e+06,-7.396774e+01,4.076792e+01,-7.396351e+01,4.076905e+01,1.076000e+03,3.943000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.290571e+07,-7.341445e+01,4.103142e+01,-7.341435e+01,4.103151e+01,4.317800e+04,6.873700e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [142]:
lngmin = min(desc.loc['min', 'start_lng'], desc.loc['min', 'end_lng'])
lngmax = max(desc.loc['max', 'start_lng'], desc.loc['max', 'end_lng'])
print(lngmin, lngmax, lngmax-lngmin)

-74.517853 -73.414352 1.103501

In [143]:
latmin = min(desc.loc['min', 'start_lat'], desc.loc['min', 'end_lat'])
latmax = max(desc.loc['max', 'start_lat'], desc.loc['max', 'end_lat'])
print(latmin, latmax, latmax-latmin)

40.368874 41.031509 0.662635

In [148]:
def get_loc(lat, lng):
    coordinates = (lat, lng)
    results = rg.search(coordinates)
    return results[0]['name'], results[0]['admin1'], results[0]['admin2']

In [153]:
c = 0
cols = ['lat', 'lng', 'region', 'admin1', 'admin2']
df_regions = pd.DataFrame(columns=cols)
for lng in np.arange(round(lngmin,2), round(lngmax,2), 0.01):
    for lat in np.arange(round(latmin,2), round(latmax,2), 0.01):
        c += 1
        if c%100==0:
            print(c, lat, lng)
        reg, adm1, adm2 = get_loc(lat, lng)
        df = pd.DataFrame([[lat, lng, reg, adm1, adm2]], columns=cols)
        df_regions = df_regions.append(df)

100 40.69 -74.51
200 41.02 -74.5
300 40.68 -74.48
400 41.01 -74.47
500 40.67 -74.45
600 41.0 -74.44
700 40.66 -74.42
800 40.99 -74.41
900 40.65 -74.39
1000 40.98 -74.38
1100 40.64 -74.36
1200 40.97 -74.35
1300 40.63 -74.33
1400 40.96 -74.32
1500 40.62 -74.3
1600 40.95 -74.29
1700 40.61 -74.27
1800 40.94 -74.26
1900 40.6 -74.24
2000 40.93 -74.23
2100 40.59 -74.21
2200 40.92 -74.2
2300 40.58 -74.18
2400 40.91 -74.17
2500 40.57 -74.15
2600 40.9 -74.14
2700 40.56 -74.12
2800 40.89 -74.11
2900 40.55 -74.09
3000 40.88 -74.08
3100 40.54 -74.06
3200 40.87 -74.05
3300 40.53 -74.03
3400 40.86 -74.02
3500 40.52 -74.0
3600 40.85 -73.99
3700 40.51 -73.97
3800 40.84 -73.96
3900 40.5 -73.94
4000 40.83 -73.93
4100 40.49 -73.91
4200 40.82 -73.9
4300 40.48 -73.88
4400 40.81 -73.87
4500 40.47 -73.85
4600 40.8 -73.84
4700 40.46 -73.82
4800 40.79 -73.81
4900 40.45 -73.79
5000 40.78 -73.78
5100 40.44 -73.76
5200 40.77 -73.75
5300 40.43 -73.73
5400 40.76 -73.72
5500 40.42 -73.7
5600 40.75 -73.69
5700 40.41 -73.67
5800 40.74 -73.66
5900 40.4 -73.64
6000 40.73 -73.63
6100 40.39 -73.61
6200 40.72 -73.6
6300 40.38 -73.58
6400 40.71 -73.57
6500 40.37 -73.55
6600 40.7 -73.54
6700 41.03 -73.53
6800 40.69 -73.51
6900 41.02 -73.5
7000 40.68 -73.48
7100 41.01 -73.47
7200 40.67 -73.45
7300 41.0 -73.44
7400 40.66 -73.42

In [154]:
df_regions.to_csv('regions.csv', index=None)

In [155]:
22

22

In [156]:
c = 0
cols = ['lat', 'lng', 'region', 'admin1', 'admin2']
df_regions = pd.DataFrame(columns=cols)
for lng in np.arange(round(lngmin,3), round(lngmax,3), 0.001):
    for lat in np.arange(round(latmin,3), round(latmax,3), 0.001):
        c += 1
        if c%100==0:
            print(c, lat, lng)
        reg, adm1, adm2 = get_loc(lat, lng)
        df = pd.DataFrame([[lat, lng, reg, adm1, adm2]], columns=cols)
        df_regions = df_regions.append(df)

100 40.468 -74.518
200 40.568 -74.518
300 40.668 -74.518
400 40.768 -74.518
500 40.868 -74.518
600 40.968 -74.518
700 40.405 -74.517
800 40.505 -74.517
900 40.605 -74.517
1000 40.705 -74.517
1100 40.805 -74.517
1200 40.905 -74.517
1300 41.005 -74.517
1400 40.442 -74.516
1500 40.542 -74.516
1600 40.642 -74.516
1700 40.742 -74.516
1800 40.842 -74.516
1900 40.942 -74.516
2000 40.379 -74.515
2100 40.479 -74.515
2200 40.579 -74.515
2300 40.679 -74.515
2400 40.779 -74.515
2500 40.879 -74.515
2600 40.979 -74.515
2700 40.416 -74.514
2800 40.516 -74.514
2900 40.616 -74.514
3000 40.716 -74.514
3100 40.816 -74.514
3200 40.916 -74.514
3300 41.016 -74.514
3400 40.453 -74.513
3500 40.553 -74.513
3600 40.653 -74.513
3700 40.753 -74.513
3800 40.853 -74.513
3900 40.953 -74.513
4000 40.39 -74.512
4100 40.49 -74.512
4200 40.59 -74.512
4300 40.69 -74.512
4400 40.79 -74.512
4500 40.89 -74.512
4600 40.99 -74.512
4700 40.427 -74.511
4800 40.527 -74.511
4900 40.627 -74.511
5000 40.727 -74.511
5100 40.827 -74.511
5200 40.927 -74.511
5300 41.027 -74.511
5400 40.464 -74.51
5500 40.564 -74.51
5600 40.664 -74.51
5700 40.764 -74.51
5800 40.864 -74.51
5900 40.964 -74.51
6000 40.401 -74.509
6100 40.501 -74.509
6200 40.601 -74.509
6300 40.701 -74.509
6400 40.801 -74.509
6500 40.901 -74.509
6600 41.001 -74.509
6700 40.438 -74.508
6800 40.538 -74.508
6900 40.638 -74.508
7000 40.738 -74.508
7100 40.838 -74.508
7200 40.938 -74.508
7300 40.375 -74.507
7400 40.475 -74.507
7500 40.575 -74.507
7600 40.675 -74.507
7700 40.775 -74.507
7800 40.875 -74.507
7900 40.975 -74.507
8000 40.412 -74.506
8100 40.512 -74.506
8200 40.612 -74.506
8300 40.712 -74.506
8400 40.812 -74.506
8500 40.912 -74.506
8600 41.012 -74.506
8700 40.449 -74.505
8800 40.549 -74.505
8900 40.649 -74.505
9000 40.749 -74.505
9100 40.849 -74.505
9200 40.949 -74.505
9300 40.386 -74.504
9400 40.486 -74.504
9500 40.586 -74.504
9600 40.686 -74.504
9700 40.786 -74.504
9800 40.886 -74.504
9900 40.986 -74.504
10000 40.423 -74.503
10100 40.523 -74.503
10200 40.623 -74.503
10300 40.723 -74.503
10400 40.823 -74.503
10500 40.923 -74.503
10600 41.023 -74.503
10700 40.46 -74.502
10800 40.56 -74.502
10900 40.66 -74.502
11000 40.76 -74.502
11100 40.86 -74.502
11200 40.96 -74.502
11300 40.397 -74.501
11400 40.497 -74.501
11500 40.597 -74.501
11600 40.697 -74.501
11700 40.797 -74.501
11800 40.897 -74.501
11900 40.997 -74.501
12000 40.434 -74.5
12100 40.534 -74.5
12200 40.634 -74.5
12300 40.734 -74.5
12400 40.834 -74.5
12500 40.934 -74.5
12600 40.371 -74.499
12700 40.471 -74.499
12800 40.571 -74.499
12900 40.671 -74.499
13000 40.771 -74.499
13100 40.871 -74.499
13200 40.971 -74.499
13300 40.408 -74.498
13400 40.508 -74.498
13500 40.608 -74.498
13600 40.708 -74.498
13700 40.808 -74.498
13800 40.908 -74.498
13900 41.008 -74.498
14000 40.445 -74.497
14100 40.545 -74.497
14200 40.645 -74.497
14300 40.745 -74.497
14400 40.845 -74.497
14500 40.945 -74.497
14600 40.382 -74.496
14700 40.482 -74.496
14800 40.582 -74.496
14900 40.682 -74.496
15000 40.782 -74.496
15100 40.882 -74.496
15200 40.982 -74.496
15300 40.419 -74.495
15400 40.519 -74.495
15500 40.619 -74.495
15600 40.719 -74.495
15700 40.819 -74.495
15800 40.919 -74.495
15900 41.019 -74.495
16000 40.456 -74.494
16100 40.556 -74.494
16200 40.656 -74.494
16300 40.756 -74.494
16400 40.856 -74.494
16500 40.956 -74.494
16600 40.393 -74.493
16700 40.493 -74.493
16800 40.593 -74.493
16900 40.693 -74.493
17000 40.793 -74.493
17100 40.893 -74.493
17200 40.993 -74.493
17300 40.43 -74.492
17400 40.53 -74.492
17500 40.63 -74.492
17600 40.73 -74.492
17700 40.83 -74.492
17800 40.93 -74.492
17900 41.03 -74.492
18000 40.467 -74.491
18100 40.567 -74.491
18200 40.667 -74.491
18300 40.767 -74.491
18400 40.867 -74.491
18500 40.967 -74.491
18600 40.404 -74.49
18700 40.504 -74.49
18800 40.604 -74.49
18900 40.704 -74.49
19000 40.804 -74.49
19100 40.904 -74.49
19200 41.004 -74.49
19300 40.441 -74.489
19400 40.541 -74.489
19500 40.641 -74.489
19600 40.741 -74.489
19700 40.841 -74.489
19800 40.941 -74.489
19900 40.378 -74.488
20000 40.478 -74.488
20100 40.578 -74.488
20200 40.678 -74.488
20300 40.778 -74.488
20400 40.878 -74.488
20500 40.978 -74.488
20600 40.415 -74.487
20700 40.515 -74.487
20800 40.615 -74.487
20900 40.715 -74.487
21000 40.815 -74.487
21100 40.915 -74.487
21200 41.015 -74.487
21300 40.452 -74.486
21400 40.552 -74.486
21500 40.652 -74.486
21600 40.752 -74.486
21700 40.852 -74.486
21800 40.952 -74.486
21900 40.389 -74.485
22000 40.489 -74.485
22100 40.589 -74.485
22200 40.689 -74.485
22300 40.789 -74.485
22400 40.889 -74.485
22500 40.989 -74.485
22600 40.426 -74.484
22700 40.526 -74.484
22800 40.626 -74.484
22900 40.726 -74.484
23000 40.826 -74.484
23100 40.926 -74.484
23200 41.026 -74.484
23300 40.463 -74.483
23400 40.563 -74.483
23500 40.663 -74.483
23600 40.763 -74.483
23700 40.863 -74.483
23800 40.963 -74.483
23900 40.4 -74.482
24000 40.5 -74.482
24100 40.6 -74.482
24200 40.7 -74.482
24300 40.8 -74.482
24400 40.9 -74.482
24500 41.0 -74.482
24600 40.437 -74.481
24700 40.537 -74.481
24800 40.637 -74.481
24900 40.737 -74.481
25000 40.837 -74.481
25100 40.937 -74.481
25200 40.374 -74.48
25300 40.474 -74.48
25400 40.574 -74.48
25500 40.674 -74.48
25600 40.774 -74.48
25700 40.874 -74.48
25800 40.974 -74.48
25900 40.411 -74.479
26000 40.511 -74.479
26100 40.611 -74.479
26200 40.711 -74.479
26300 40.811 -74.479
26400 40.911 -74.479
26500 41.011 -74.479
26600 40.448 -74.478
26700 40.548 -74.478
26800 40.648 -74.478
26900 40.748 -74.478
27000 40.848 -74.478
27100 40.948 -74.478
27200 40.385 -74.477
27300 40.485 -74.477
27400 40.585 -74.477
27500 40.685 -74.477
27600 40.785 -74.477
27700 40.885 -74.477
27800 40.985 -74.477
27900 40.422 -74.476
28000 40.522 -74.476
28100 40.622 -74.476
28200 40.722 -74.476
28300 40.822 -74.476
28400 40.922 -74.476
28500 41.022 -74.476
28600 40.459 -74.475
28700 40.559 -74.475
28800 40.659 -74.475
28900 40.759 -74.475
29000 40.859 -74.475
29100 40.959 -74.475
29200 40.396 -74.474
29300 40.496 -74.474
29400 40.596 -74.474
29500 40.696 -74.474
29600 40.796 -74.474
29700 40.896 -74.474
29800 40.996 -74.474
29900 40.433 -74.473
30000 40.533 -74.473
30100 40.633 -74.473
30200 40.733 -74.473
30300 40.833 -74.473
30400 40.933 -74.473
30500 40.37 -74.472
30600 40.47 -74.472
30700 40.57 -74.472
30800 40.67 -74.472
30900 40.77 -74.472
31000 40.87 -74.472
31100 40.97 -74.472
31200 40.407 -74.471
31300 40.507 -74.471
31400 40.607 -74.471
31500 40.707 -74.471
31600 40.807 -74.471
31700 40.907 -74.471
31800 41.007 -74.471
31900 40.444 -74.47
32000 40.544 -74.47
32100 40.644 -74.47
32200 40.744 -74.47
32300 40.844 -74.47
32400 40.944 -74.47
32500 40.381 -74.469
32600 40.481 -74.469
32700 40.581 -74.469
32800 40.681 -74.469
32900 40.781 -74.469
33000 40.881 -74.469
33100 40.981 -74.469
33200 40.418 -74.468
33300 40.518 -74.468
33400 40.618 -74.468
33500 40.718 -74.468
33600 40.818 -74.468
33700 40.918 -74.468
33800 41.018 -74.468
33900 40.455 -74.467
34000 40.555 -74.467
34100 40.655 -74.467
34200 40.755 -74.467
34300 40.855 -74.467
34400 40.955 -74.467
34500 40.392 -74.466
34600 40.492 -74.466
34700 40.592 -74.466
34800 40.692 -74.466
34900 40.792 -74.466
35000 40.892 -74.466
35100 40.992 -74.466
35200 40.429 -74.465
35300 40.529 -74.465
35400 40.629 -74.465
35500 40.729 -74.465
35600 40.829 -74.465
35700 40.929 -74.465
35800 41.029 -74.465
35900 40.466 -74.464
36000 40.566 -74.464
36100 40.666 -74.464
36200 40.766 -74.464
36300 40.866 -74.464
36400 40.966 -74.464
36500 40.403 -74.463
36600 40.503 -74.463
36700 40.603 -74.463
36800 40.703 -74.463
36900 40.803 -74.463
37000 40.903 -74.463
37100 41.003 -74.463
37200 40.44 -74.462
37300 40.54 -74.462
37400 40.64 -74.462
37500 40.74 -74.462
37600 40.84 -74.462
37700 40.94 -74.462
37800 40.377 -74.461
37900 40.477 -74.461
38000 40.577 -74.461
38100 40.677 -74.461
38200 40.777 -74.461
38300 40.877 -74.461
38400 40.977 -74.461
38500 40.414 -74.46
38600 40.514 -74.46
38700 40.614 -74.46
38800 40.714 -74.46
38900 40.814 -74.46
39000 40.914 -74.46
39100 41.014 -74.46
39200 40.451 -74.459
39300 40.551 -74.459
39400 40.651 -74.459
39500 40.751 -74.459
39600 40.851 -74.459
39700 40.951 -74.459
39800 40.388 -74.458
39900 40.488 -74.458
40000 40.588 -74.458

40100 40.688 -74.458
40200 40.788 -74.458
40300 40.888 -74.458
40400 40.988 -74.458
40500 40.425 -74.457
40600 40.525 -74.457
40700 40.625 -74.457
40800 40.725 -74.457
40900 40.825 -74.457
41000 40.925 -74.457
41100 41.025 -74.457
41200 40.462 -74.456
41300 40.562 -74.456
41400 40.662 -74.456
41500 40.762 -74.456
41600 40.862 -74.456
41700 40.962 -74.456
41800 40.399 -74.455
41900 40.499 -74.455
42000 40.599 -74.455
42100 40.699 -74.455
42200 40.799 -74.455
42300 40.899 -74.455
42400 40.999 -74.455
42500 40.436 -74.454
42600 40.536 -74.454
42700 40.636 -74.454
42800 40.736 -74.454
42900 40.836 -74.454
43000 40.936 -74.454
43100 40.373 -74.453
43200 40.473 -74.453
43300 40.573 -74.453
43400 40.673 -74.453
43500 40.773 -74.453
43600 40.873 -74.453
43700 40.973 -74.453
43800 40.41 -74.452
43900 40.51 -74.452
44000 40.61 -74.452
44100 40.71 -74.452
44200 40.81 -74.452
44300 40.91 -74.452
44400 41.01 -74.452
44500 40.447 -74.451
44600 40.547 -74.451
44700 40.647 -74.451
44800 40.747 -74.451
44900 40.847 -74.451
45000 40.947 -74.451
45100 40.384 -74.45
45200 40.484 -74.45
45300 40.584 -74.45
45400 40.684 -74.45
45500 40.784 -74.45
45600 40.884 -74.45
45700 40.984 -74.45
45800 40.421 -74.449
45900 40.521 -74.449
46000 40.621 -74.449
46100 40.721 -74.449
46200 40.821 -74.449
46300 40.921 -74.449
46400 41.021 -74.449
46500 40.458 -74.448
46600 40.558 -74.448
46700 40.658 -74.448
46800 40.758 -74.448
46900 40.858 -74.448
47000 40.958 -74.448
47100 40.395 -74.447
47200 40.495 -74.447
47300 40.595 -74.447
47400 40.695 -74.447
47500 40.795 -74.447
47600 40.895 -74.447
47700 40.995 -74.447
47800 40.432 -74.446
47900 40.532 -74.446
48000 40.632 -74.446
48100 40.732 -74.446
48200 40.832 -74.446
48300 40.932 -74.446
48400 40.369 -74.445
48500 40.469 -74.445
48600 40.569 -74.445
48700 40.669 -74.445
48800 40.769 -74.445
48900 40.869 -74.445
49000 40.969 -74.445
49100 40.406 -74.444
49200 40.506 -74.444
49300 40.606 -74.444
49400 40.706 -74.444
49500 40.806 -74.444
49600 40.906 -74.444
49700 41.006 -74.444
49800 40.443 -74.443
49900 40.543 -74.443
50000 40.643 -74.443
50100 40.743 -74.443
50200 40.843 -74.443
50300 40.943 -74.443
50400 40.38 -74.442
50500 40.48 -74.442
50600 40.58 -74.442
50700 40.68 -74.442
50800 40.78 -74.442
50900 40.88 -74.442
51000 40.98 -74.442
51100 40.417 -74.441
51200 40.517 -74.441
51300 40.617 -74.441
51400 40.717 -74.441
51500 40.817 -74.441
51600 40.917 -74.441
51700 41.017 -74.441
51800 40.454 -74.44
51900 40.554 -74.44
52000 40.654 -74.44
52100 40.754 -74.44
52200 40.854 -74.44
52300 40.954 -74.44
52400 40.391 -74.439
52500 40.491 -74.439
52600 40.591 -74.439
52700 40.691 -74.439
52800 40.791 -74.439
52900 40.891 -74.439
53000 40.991 -74.439
53100 40.428 -74.438
53200 40.528 -74.438
53300 40.628 -74.438
53400 40.728 -74.438
53500 40.828 -74.438
53600 40.928 -74.438
53700 41.028 -74.438
53800 40.465 -74.437
53900 40.565 -74.437
54000 40.665 -74.437
54100 40.765 -74.437
54200 40.865 -74.437
54300 40.965 -74.437
54400 40.402 -74.436
54500 40.502 -74.436
54600 40.602 -74.436
54700 40.702 -74.436
54800 40.802 -74.436
54900 40.902 -74.436
55000 41.002 -74.436
55100 40.439 -74.435
55200 40.539 -74.435
55300 40.639 -74.435
55400 40.739 -74.435
55500 40.839 -74.435
55600 40.939 -74.435
55700 40.376 -74.434
55800 40.476 -74.434
55900 40.576 -74.434
56000 40.676 -74.434
56100 40.776 -74.434
56200 40.876 -74.434
56300 40.976 -74.434
56400 40.413 -74.433
56500 40.513 -74.433
56600 40.613 -74.433
56700 40.713 -74.433
56800 40.813 -74.433
56900 40.913 -74.433
57000 41.013 -74.433
57100 40.45 -74.432
57200 40.55 -74.432
57300 40.65 -74.432
57400 40.75 -74.432
57500 40.85 -74.432
57600 40.95 -74.432
57700 40.387 -74.431
57800 40.487 -74.431
57900 40.587 -74.431
58000 40.687 -74.431
58100 40.787 -74.431
58200 40.887 -74.431
58300 40.987 -74.431
58400 40.424 -74.43
58500 40.524 -74.43
58600 40.624 -74.43
58700 40.724 -74.43
58800 40.824 -74.43
58900 40.924 -74.43
59000 41.024 -74.43
59100 40.461 -74.429
59200 40.561 -74.429
59300 40.661 -74.429
59400 40.761 -74.429
59500 40.861 -74.429
59600 40.961 -74.429
59700 40.398 -74.428
59800 40.498 -74.428
59900 40.598 -74.428
60000 40.698 -74.428
60100 40.798 -74.428
60200 40.898 -74.428
60300 40.998 -74.428
60400 40.435 -74.427
60500 40.535 -74.427
60600 40.635 -74.427
60700 40.735 -74.427
60800 40.835 -74.427
60900 40.935 -74.427
61000 40.372 -74.426
61100 40.472 -74.426

KeyboardInterrupt: